name: Frontend CI & Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug folder structure
        run: ls -R .

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "Caremoms-frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./Caremoms-frontend
        run: npm ci

      - name: Run tests
        working-directory: ./Caremoms-frontend
        run: npm test -- --watchAll=false

      - name: Build frontend
        working-directory: ./Caremoms-frontend
        run: npm run build
